server:
  port: 8001
  context-path: /spring-cloud-eureka-producer

spring:
  application:
    name: spring-cloud-eureka-producer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/