server:
  port: 8001
#  context-path: /spring-cloud-eureka-producer

spring:
  application:
    name: spring-cloud-eureka-producer
  zipkin:
    base-url: http://localhost:8006
  sleuth:
    sampler:
      percentage: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

