server:
  port: 8004
  context-path: /spring-cloud-config-client

spring:
  application:
    name: spring-cloud-config-client

management:
  security:
    enabled: false # springboot 1.5.X 以上默认开通了安全认证,此处先关闭