server:
  port: 8002
  context-path: /spring-cloud-eureka-consumer

spring:
  application:
    name: spring-cloud-eureka-consumer
  zipkin:
    base-url: http://localhost:8006
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true