server:
  port: 8002
  context-path: /spring-cloud-eureka-consumer

spring:
  application:
    name: spring-cloud-eureka-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true